### ISSUE TITLE
Info photo vide dans api/bbox avec comms

### ISSUE THREAD

**Issue by Dominique92** [sletuffe/www.refuges.info#37]
http://www.refuges.info/api/bbox?bbox=world&detail=complet&nb_coms=100
Donne systématiquement: photo":{"nb":1,"date":"2011-11-17","reduite":null,"originale":null}
Ne devrait il pas donner le lien vers les photos au lieu du null ?

**Comment by LeOSW42** [comment]
Je pense que c'est parce qu'on utilise la base de test et que nous n'avons pas les path vers les images.
Je teste en prod ;)

**Comment by LeOSW42** [comment]
Testé en prod, ce n'est pas un problème de répertoire d'images

**Comment by LeOSW42** [comment]
En fait j'ai pas vraiment résolu le problème. Pour les exports d'une liste de points (massif ou bbox) ça ne marche toujours pas
