### ISSUE TITLE
Carte inaccessible en modif de point dans les zones de développement 

### ISSUE THREAD

**Issue by sletuffe** [sletuffe/www.refuges.info#40]
http://sly.refuges.info/point_formulaire_modification.php?id_point=4062

Pour bing j'avais compris que c'est l'histoire des clés, mais pour les cartes basées osm ?

Ça me permettrait de faire des tests plus simplement sur ma zone de dév

**Comment by Dominique92** [comment]
C'est un bug que j'avais vu en passant mais que je n'ai jamais corrigé (pas prioritaire): quand LL n'arrive pas à se connecter sur la première couche demandée (ici bing où ta clé est nulle), le layerswitcher ne sait pas passer à une autre carte (en fait, il ne sait pas sortir de la première !! )
Met la clé bing du site de prod (elle est générique) ça devrait aller mieux,
Je t'ai demandé une clé sly.r.i mais elle ne sera activée que demain.

**Comment by sletuffe** [comment]
Nikel, ça marche simplement en ajoutant :
$config['bing_key']='AqTGBsziZHIJYYxgivLBf0hVdrAk9mWO5cQcb8Yux8sW5M8c8opEC2lZqKR1ZZXf'; 

Inutile de m'activer une clé spécifique non ?

Je clos le bug

**Comment by Dominique92** [comment]
En fait, j’ai demandé 1 clé 1 fois (en donnant mon mail) et elle marche sur tous mes sites.
Je suppose qu’elle m’identifie personnellement en cas de pb et non le site qui l’utilise. Aucune limite de capacité, temps, …
