### ISSUE TITLE
gestion de l'obscurcissement de numéro de téléphone dans bbcode2html

### ISSUE THREAD

**Issue by sletuffe** [sletuffe/www.refuges.info#42]
l'expression régulière était un peu trop généreuse avec : 0[0-9]([-. ]?[0-9]{2}){4}

car ça chopait des URL à rallonge que j'avais mis dans le wiki car elle ressemblait à :
http://www.legifrance.gouv.fr/affichCode&cidTexte=LEGITEXT000006074073
ça chopait le texte de l'url car il avait 10 chiffres d'affilé

exemple :
http://sly.refuges.info/wiki/fiche-refuge-garde2

j'ai renforcé par [^0-9A-Za-z](0[0-9]([-. ]?[0-9]{2}){4})[^0-9]
mais c'est pas terrible, ça ne match plus les numéros suisses par exemple.
de plus, ça ne gérait pas non plus le format +33 645754575

**Comment by sletuffe** [comment]
bordel de github de m... qui me bouffe mes expression régulière
Là : https://github.com/sletuffe/www.refuges.info/blob/master/includes/mise_en_forme_texte.php#L176

**Comment by LeOSW42** [comment]
On peut fermer le bug ?

**Comment by sletuffe** [comment]
Tout à fait, je suis motivé pour du ménage afin qu'on y voit plus clair !

J'ai surtout voulu vous indiquer que cette fonction, bien qu'ayant corrigé le problème que je rencontrais, souffre toujours de "limitations". Mais un FIXME dans le code suffit
