### ISSUE TITLE
l'api ne fonctionne qu'à la racine

### ISSUE THREAD

**Issue by Dominique92** [sletuffe/www.refuges.info#43]
Contrairement au reste du site, impossible de déraciner l'API
Il faut revoir le .htaccess
RewriteRule . /api/routing.php [L]

**Comment by Dominique92** [comment]
Livré commit 90fbbe59008375262d0a76eba54f7a225f40d3fa

**Comment by sletuffe** [comment]
ça me semble étrange qu'on soit obligé de gérer l'api différemment du reste, toute notre tambouille de routes et de mvc à justement pour but supplémentaire de factoriser, et que lorsque l'on change le fichier config de dossier on ne soit pas obligé de repasser dans x fichiers mais 1 seul (bon, forum en rab comme d'hab)
Idem .htaccess, on ne devrait pas, à mon sens, s'en retrouver avec un par dossier qui ne sont que des copier coller de celui sur /

Je ré-ouvre pour tenter de proposer quelque chose

**Comment by Dominique92** [comment]
Oui bizarre. Je n'ai jamais vu de pb de ce genre. Tout le code devrait être relatif. Même le forum, qui a été écris en relatif pose problème ici.
Et franchement, tous ces répertoires définis en config.php, c'est relou.
Je n'ai jamais un sous domaine à moi tout seul quand je développe. Il faut et il suffit d'avoir tous ses liens en relatif mais, pour ça, il faudrait tout reprendre.
Je pense que le plus dur est l'URL simplifié. Il faut commencer à réfléchir par là (et voir comment les autres CMS qui pratiquent l'URL simplifié ont résolu la question). Une fois résolu ce point avec un .htaccess et un point d'entrée unique qui va bien, le reste devrait découler sans pb.

**Comment by LeOSW42** [comment]
En effet, nous ne sommes pas du tout obligé de séparer les .htaccess

J'avais fait ça pour pas avoir de conflit de merge une fois l'API
terminée (ne sachant pas combien de temps ça allait me prendre et si le
.htaccess de la racine allait évoluer)

Léo

Le 25/01/2015 21:56, Dominique92 a écrit :
>
> Oui bizarre. Je n'ai jamais vu de pb de ce genre. Tout le code devrait
> être relatif. Même le forum, qui a été écris en relatif pose problème ici.
> Et franchement, tous ces répertoires définis en config.php, c'est relou.
> Je n'ai jamais un sous domaine à moi tout seul quand je développe. Il
> faut et il suffit d'avoir tous ses liens en relatif mais, pour ça, il
> faudrait tout reprendre.
> Je pense que le plus dur est l'URL simplifié. Il faut commencer à
> réfléchir par là (et voir comment les autres CMS qui pratiquent l'URL
> simplifié ont résolu la question). Une fois résolu ce point avec un
> .htaccess et un point d'entrée unique qui va bien, le reste devrait
> découler sans pb.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sletuffe/www.refuges.info/issues/43#issuecomment-71393115>.
>

-- 
Léo SERRE
  06.18.62.32.05
  leo-serre.legtux.org

**Comment by Dominique92** [comment]
Ceci dit, rien de grave. Tout est fonctionnel :)
Je ne suis pas sur que réécrire WRI en permanence soit une priorité.

**Comment by sletuffe** [comment]
Pour la remarque de dominique, moi, j'ai vu plusieurs fois des problèmes de ce genre (dans les applicatifs php libres) où le chemin de l'application doit être indiqué quelque part et ensuite un endroit dans lequel on définit le chemin d'installation relatif à "/" 
Le "setup" de l'application se charge de détecter ça, mais sitôt qu'on décide de renommer le dossier, il faut remettre à jour.

bref, en effet, rien de grave, vu que ça marche, mais autant que l'on factorise au max pour n'avoir qu'un seul endroit où changer le chemin

**Comment by sletuffe** [comment]
Voilà une proposition pour rendre le déracinage compatible + ne pas faire de dossier /api et ranger les routes dans /routes (on peut ajouter des nouveaux fichiers au besoin si par exemple on veut avoir /toto/X et mettre toutes les routes /toto dans un fichier séparé.

**Comment by sletuffe** [comment]
là :
https://github.com/sletuffe/www.refuges.info/commit/b54965ba3713b3b1e35f12153faaab6c20f875a0
et
là :
https://github.com/sletuffe/www.refuges.info/commit/4e2d49d919dbdc745d0c9dc704cda74d44edab33

**Comment by Dominique92** [comment]
Je pensais plus compact:
include($wri/api/points.vue.rss");
copy($photo_a_conserver, "$install$wri/$commentaire->id_commentaire.jpeg");

Avec $install = "/home/users/dom/www.refuges.info/" et $wri = la racine (par exemple "") détecté dans /routage.php

**Comment by sletuffe** [comment]
Je ne suis pas sûr de comprendre ton "plus compact", c'est bien comme ça qu'on fait déjà non ?

Ou alors tu parles de simplifier le nom de la variable en $wri plutôt que $config['racine_projet'] ?

**Comment by Dominique92** [comment]
Oui. C'est tout !
Mais ça permet de les insérer dans une chaine ""

**Comment by sletuffe** [comment]
Nous avons alors un peu dévié de la question initiale concernant l'api et l'installation en sous-dossier puis factorisation.
je déplace ici : #45

**Comment by sletuffe** [comment]
Je ne constate pas de bugs pour l'instant suite à ces modifs, je clos donc
