### ISSUE TITLE
Variable d'accès aux chemins d'installation plus comptacte

### ISSUE THREAD

**Issue by sletuffe** [sletuffe/www.refuges.info#45]
Dominique92 :

Je pensais plus compact:
include("$wri/api/points.vue.rss");
copy($photo_a_conserver, "$install/$wri/$commentaire->id_commentaire.jpeg");

Avec $install = "/home/users/dom/www.refuges.info" et $wri = la racine (par exemple "") détecté dans /routage.php

**Comment by sletuffe** [comment]
Je ne suis pas sûr de comprendre ton "plus compact", c'est bien comme ça qu'on fait déjà non ?

Ou alors tu parles de simplifier le nom de la variable en $wri plutôt que $config['racine_projet'] ?

**Comment by sletuffe** [comment]
Dominique92 :

Oui. C'est tout !
Mais ça permet de les insérer dans une chaine ""

**Comment by sletuffe** [comment]
Certes, mais en contrepartie, dans chaque fonction il faudra déclarer la variable $wri puis $install comme global si on veut accéder à cette variable.

C'est pas par plaisir que je me tape des variables aussi pénibles à écrire ! C'est qu'avec le tableau $config je factorise l'appel dans les fonctions.

**Comment by Dominique92** [comment]
Bonne remarque. Pas pensé à ça :(
